### ISSUE TITLE
Towards the next release (0.1.17): open PR's and things to do

### ISSUE THREAD

**Issue by flinz** [rossp/django-helpdesk#362]
Hey @rossp, I think we might be collecting a few compatibility PR's that would probably merit a new release, keeping up with Django versions as well as adding Python3 compatibility. 

Since it was a little confusing to me, I chose to start this issue - here's a little overview of open PR's and related things to do towards a release. Would you have any thoughts or extensions on what we should include? 

Maybe it would be worth opening a milestone for the next release and add these todo items as issues, to sort this out a little?

 - [x] Update docs & installers to only support Python 2.7/3.3-3.5 (Issue: https://github.com/rossp/django-helpdesk/issues/290, PR: https://github.com/rossp/django-helpdesk/pull/356)
 - [x] Update docs & installers to only support Django>=1.7 (Issue: https://github.com/rossp/django-helpdesk/issues/355, PR: https://github.com/rossp/django-helpdesk/pull/358)
 - [x] Update travis testing to include Python 2.7 as well as 3.3-3.5
 - [x] Update travis testing to include Django 1.7, 1.8 & 1.9
 - [x] Fix broken tests :) https://travis-ci.org/rossp/django-helpdesk/builds/97108228
 - [ ] Couple days quick testing
 - [ ] Update release approx ETA 21st December 2016

**Comment by rossp** [comment]
I've merged the big changes for Django 1.9 and Python 3.

Let's give this a couple of days then update the Pypi release - would rather get some more thorough testing of both of these done prior to updating the installer.

Note Travis is currently failing on some combos of Django >=1.8 and Python 3. Needs quick review.

 - [x] Update docs & installers to only support Python 2.7/3.3-3.5 (Issue: https://github.com/rossp/django-helpdesk/issues/290, PR: https://github.com/rossp/django-helpdesk/pull/356)
 - [x] Update docs & installers to only support Django>=1.7 (Issue: https://github.com/rossp/django-helpdesk/issues/355, PR: https://github.com/rossp/django-helpdesk/pull/358)
 - [x] Update travis testing to include Python 2.7 as well as 3.3-3.5
 - [x] Update travis testing to include Django 1.7, 1.8 & 1.9
 - [ ] Fix broken tests :) https://travis-ci.org/rossp/django-helpdesk/builds/97108228
 - [ ] Couple days quick testing
 - [ ] Update release approx ETA 21st December 2016

**Comment by flinz** [comment]
this is a little weird. most of the python 3 errors are due to errors involving this 
```python
 File "/home/travis/build/rossp/django-helpdesk/helpdesk/lib.py", line 110, in send_templated_mail
    if context.has_key('comment'):
AttributeError: 'dict' object has no attribute 'has_key'
```

however the master branch has this already fixed (this was changed in the python3 PR):
https://github.com/rossp/django-helpdesk/blob/master/helpdesk/lib.py#L110 reads
```python
if 'comment' in context:
...
```

**Comment by flinz** [comment]
Also, I just did a quick check:
It seems python 3.2 and 3.3 support have been dropped as of django 1.8
```
Django 1.9 requires Python 2.7, 3.4, or 3.5. We highly recommend and only officially support the latest release of each series. Since Django 1.8, we’ve dropped support for Python 3.2 and 3.3.
```

This was my bad for overlooking, sorry. We should specify minimum requirements python 3.4 and remove 3.3 from the travis builds.

**Comment by flinz** [comment]
Only one error remaining, and it's a known error with Django 1.7 and Python 3.5.. https://code.djangoproject.com/ticket/23763 or http://www.thefourtheye.in/2015/02/python-35-and-django-17s-htmlparseerror.html

What should we do about this? Probably remove that particular combination from the travis build and change supported versions to exclude 1.7 + 3.5.

**Comment by flinz** [comment]
Aaand, we're green across the board.
\**cracks open the champagne*\*

**Comment by rossp** [comment]
- [x] Update docs & installers to only support Python 2.7/3.3-3.5 (Issue: https://github.com/rossp/django-helpdesk/issues/290, PR: https://github.com/rossp/django-helpdesk/pull/356)
 - [x] Update docs & installers to only support Django>=1.7 (Issue: https://github.com/rossp/django-helpdesk/issues/355, PR: https://github.com/rossp/django-helpdesk/pull/358)
 - [x] Update travis testing to include Python 2.7 as well as 3.3-3.5
 - [x] Update travis testing to include Django 1.7, 1.8 & 1.9
 - [x] Fix broken tests :) https://travis-ci.org/rossp/django-helpdesk/builds/97108228
 - [ ] Couple days quick testing
 - [ ] Update release approx ETA 21st December 2016

**Comment by rossp** [comment]
Thanks so much for your help getting this over the line. It's long overdue.

I'll try to do some testing in the next 3-4 days then do a new release early next week.

**Comment by flinz** [comment]
No problem, happy to help out! Let me know if anything comes up.

**Comment by flinz** [comment]
@rossp I am not sure whether you want to get https://github.com/rossp/django-helpdesk/pull/367 into the release, but then we should merge in addition 
- https://github.com/rossp/django-helpdesk/pull/367
- https://github.com/rossp/django-helpdesk/pull/369
- https://github.com/rossp/django-helpdesk/pull/370
- https://github.com/rossp/django-helpdesk/pull/373

**Comment by rando305** [comment]
Much appreciated!

**Comment by rossp** [comment]
@flinz they're all merged in. Pypi release on it's way tonight since we haven't had anything major come up :)

**Comment by flinz** [comment]
@rossp sounds good!

**Comment by flinz** [comment]
@rossp Congrats! Want to add a tag too?

**Comment by rossp** [comment]
@flinz oops good catch - tag added. Thanks :)
